name: "keycloak-poc"

services:
  keycloak:
    build:
      context: ./keycloak/
    ports:
      - '8080:8080'
      - '9000:9000'
    depends_on:
      - postgres
      - infinispan

  infinispan:
    build:
      context: ./infinispan/
    ports:
      - '11222:11222'

  postgres:
    build:
      context: ./postgres/
    ports:
      - '5432:5432'
    healthcheck:
      test: psql postgres --command "select 1" -U postgres      
